include: package:flutter_lints/flutter.yaml

analyzer:
  # exclude:
  # None for now
  errors:
    always_declare_return_types: info
    always_put_control_body_on_new_line: ignore
    always_put_required_named_parameters_first: info
    always_require_non_null_named_parameters: info
    always_specify_types: ignore
    always_use_package_imports: ignore
    annotate_overrides: ignore
    annotate_redeclares: info
    avoid_annotating_with_dynamic: ignore
    avoid_as: info
    avoid_bool_literals_in_conditional_expressions: info
    avoid_catches_without_on_clauses: info
    avoid_catching_errors: info
    avoid_classes_with_only_static_members: info
    avoid_double_and_int_checks: info
    avoid_dynamic_calls: info
    avoid_empty_else: info
    avoid_equals_and_hash_code_on_mutable_classes: info
    avoid_escaping_inner_quotes: info
    avoid_field_initializers_in_const_classes: info
    # avoid_final_parameters: ignore # Incompatible with the rule prefer_final_parameters
    avoid_function_literals_in_foreach_calls: info
    avoid_implementing_value_types: info
    avoid_init_to_null: info
    avoid_js_rounded_ints: info
    avoid_multiple_declarations_per_line: info
    avoid_null_checks_in_equality_operators: info
    avoid_positional_boolean_parameters: info
    avoid_print: info
    avoid_private_typedef_functions: info
    avoid_redundant_argument_values: info
    avoid_relative_lib_imports: info
    avoid_renaming_method_parameters: info
    avoid_return_types_on_setters: info
    avoid_returning_null: info
    avoid_returning_null_for_future: info
    avoid_returning_null_for_void: info
    avoid_returning_this: info
    avoid_setters_without_getters: info
    avoid_shadowing_type_parameters: info
    avoid_single_cascade_in_expression_statements: info
    avoid_slow_async_io: info
    avoid_type_to_string: info
    avoid_types_as_parameter_names: info
    # avoid_types_on_closure_parameters: info # This rule is incompatable always_specify_types
    avoid_unnecessary_containers: info
    # avoid_unstable_final_fields: ignore # This rule is currently experimental and not yet available in a stable SDK.
    avoid_unused_constructor_parameters: info
    avoid_void_async: info
    avoid_web_libraries_in_flutter: info
    await_only_futures: info
    camel_case_extensions: info
    camel_case_types: info
    cancel_subscriptions: info
    cascade_invocations: info
    cast_nullable_to_non_nullable: info
    close_sinks: info
    collection_methods_unrelated_type: info
    combinators_ordering: info
    comment_references: info
    conditional_uri_does_not_exist: info
    constant_identifier_names: info
    control_flow_in_finally: info
    curly_braces_in_flow_control_structures: info
    dangling_library_doc_comments: info
    depend_on_referenced_packages: info
    deprecated_consistency: info
    deprecated_member_use_from_same_package: info
    diagnostic_describe_all_properties: ignore
    directives_ordering: info
    discarded_futures: ignore # TODO(any): enable this rule in the future after fixing ~XX issues
    do_not_use_environment: info
    empty_catches: info
    empty_constructor_bodies: info
    empty_statements: info
    eol_at_end_of_file: info
    exhaustive_cases: info
    file_names: info
    flutter_style_todos: info
    hash_and_equals: info
    implementation_imports: info
    implicit_call_tearoffs: info
    implicit_reopen: info
    invalid_case_patterns: info
    join_return_with_assignment: info
    leading_newlines_in_multiline_strings: info
    library_annotations: info
    library_names: info
    library_prefixes: info
    library_private_types_in_public_api: info
    lines_longer_than_80_chars: info
    literal_only_boolean_expressions: info
    matching_super_parameters: info
    missing_whitespace_between_adjacent_strings: info
    no_adjacent_strings_in_list: info
    no_default_cases: ignore
    no_duplicate_case_values: info
    no_leading_underscores_for_library_prefixes: info
    no_leading_underscores_for_local_identifiers: info
    no_literal_bool_comparisons: info
    no_logic_in_create_state: info
    no_runtimeType_toString: info
    no_self_assignments: info
    no_wildcard_variable_uses: info
    non_constant_identifier_names: info
    noop_primitive_operations: info
    null_check_on_nullable_type_parameter: info
    null_closures: info
    # omit_local_variable_types: ignore
    one_member_abstracts: info
    only_throw_errors: info
    overridden_fields: info
    package_api_docs: info
    package_names: info
    package_prefixed_library_names: info
    parameter_assignments: info
    prefer_adjacent_string_concatenation: info
    prefer_asserts_in_initializer_lists: info
    prefer_asserts_with_message: info
    prefer_collection_literals: info
    prefer_conditional_assignment: info
    prefer_const_constructors: info
    prefer_const_constructors_in_immutables: info
    prefer_const_declarations: info
    prefer_const_literals_to_create_immutables: info
    prefer_constructors_over_static_methods: info
    prefer_contains: info
    prefer_expression_function_bodies: ignore
    prefer_final_fields: info
    prefer_final_in_for_each: info
    prefer_final_locals: info
    prefer_final_parameters: ignore # TODO(any): Enable this rule if desired after fixing ~XXX issues
    prefer_for_elements_to_map_fromIterable: info
    prefer_foreach: info
    prefer_function_declarations_over_variables: info
    prefer_generic_function_type_aliases: info
    prefer_if_elements_to_conditional_expressions: ignore
    prefer_if_null_operators: info
    prefer_initializing_formals: info
    prefer_inlined_adds: info
    prefer_int_literals: info
    prefer_interpolation_to_compose_strings: info
    prefer_is_empty: info
    prefer_is_not_empty: info
    prefer_is_not_operator: info
    prefer_iterable_whereType: info
    prefer_mixin: info
    prefer_null_aware_method_calls: info
    prefer_null_aware_operators: info
    # prefer_relative_imports: ignore # Incompatible with the rule always_use_package_imports.
    prefer_single_quotes: info
    prefer_spread_collections: info
    prefer_typing_uninitialized_variables: info
    prefer_void_to_null: info
    provide_deprecation_message: info
    public_member_api_docs: ignore
    recursive_getters: info
    require_trailing_commas: info
    secure_pubspec_urls: info
    sized_box_for_whitespace: info
    sized_box_shrink_expand: info
    slash_for_doc_comments: info
    sort_child_properties_last: info
    sort_constructors_first: ignore
    sort_pub_dependencies: info
    sort_unnamed_constructors_first: info
    test_types_in_equals: info
    throw_in_finally: info
    tighten_type_of_initializing_formals: info
    type_annotate_public_apis: ignore
    type_init_formals: info
    type_literal_in_constant_pattern: info
    unawaited_futures: ignore
    unnecessary_await_in_return: info
    unnecessary_brace_in_string_interps: info
    unnecessary_breaks: info
    unnecessary_const: info
    unnecessary_constructor_name: info
    # unnecessary_final: ignore # Incompatible with the rule prefer_final_locals
    unnecessary_getters_setters: info
    unnecessary_lambdas: info
    unnecessary_late: info
    unnecessary_library_directive: info
    unnecessary_new: info
    unnecessary_null_aware_assignments: info
    unnecessary_null_aware_operator_on_extension_on_nullable: info
    unnecessary_null_checks: info
    unnecessary_null_in_if_null_operators: info
    unnecessary_nullable_for_final_variable_declarations: info
    unnecessary_overrides: info
    unnecessary_parenthesis: info
    unnecessary_raw_strings: info
    unnecessary_statements: info
    unnecessary_string_escapes: info
    unnecessary_string_interpolations: info
    unnecessary_this: info
    unnecessary_to_list_in_spreads: info
    unreachable_from_main: info
    unrelated_type_equality_checks: info
    unsafe_html: info
    use_build_context_synchronously: info
    use_colored_box: info
    use_decorated_box: info
    use_enums: info
    use_full_hex_values_for_flutter_colors: info
    use_function_type_syntax_for_parameters: info
    use_if_null_to_convert_nulls_to_bools: info
    use_is_even_rather_than_modulo: info
    use_key_in_widget_constructors: info
    use_late_for_private_fields_and_variables: info
    use_named_constants: info
    use_raw_strings: info
    use_rethrow_when_possible: info
    use_setters_to_change_properties: info
    use_string_buffers: info
    use_string_in_part_of_directives: info
    use_super_parameters: info
    use_test_throws_matchers: info
    use_to_and_as_if_applicable: info
    valid_regexps: info
    void_checks: info

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - always_specify_types
    - always_use_package_imports
    - annotate_overrides
    - annotate_redeclares
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    # - avoid_final_parameters # Incompatible with the rule prefer_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    # - avoid_types_on_closure_parameters # Incompatible with the rule always_specify_types
    - avoid_unnecessary_containers
    # - avoid_unstable_final_fields
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - dangling_library_doc_comments
    - depend_on_referenced_packages
    - deprecated_consistency
    - deprecated_member_use_from_same_package
    - diagnostic_describe_all_properties
    - directives_ordering
    - discarded_futures
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    - implicit_call_tearoffs
    - implicit_reopen
    - invalid_case_patterns
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_annotations
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - lines_longer_than_80_chars
    - literal_only_boolean_expressions
    - matching_super_parameters
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_default_cases
    - no_duplicate_case_values
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - no_literal_bool_comparisons
    - no_logic_in_create_state
    - no_runtimeType_toString
    - no_self_assignments
    - no_wildcard_variable_uses
    - non_constant_identifier_names
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - null_closures
    # - omit_local_variable_types # Incompatible with the rule always_specify_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    # - prefer_double_quotes
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    # - prefer_relative_imports # Incompatible with the rule always_use_package_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    - public_member_api_docs
    - recursive_getters
    - require_trailing_commas
    - secure_pubspec_urls
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_init_formals
    - type_literal_in_constant_pattern
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    # - unnecessary_final # Incompatible with the rule prefer_final_locals
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_library_directive
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - unreachable_from_main
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks